#!/bin/bash

# Get the directory of the current script
SCRIPT_DIR=$(dirname "$(realpath "$0")")

# Base directory where dotfiles are located
DOTFILES_DIR="$SCRIPT_DIR/.config"

# Target directory where dotfiles will be stowed
TARGET_DIR="$HOME/.config"

# Ensure the target directory exists
mkdir -p "$TARGET_DIR"

# List of directories to be stowed
DOTFILES_DIRS=(
    "alacritty"
    "dunst"
    "gtk"
    "i3"
    "neofetch"
    "nvim"
    "picom"
    "polybar"
    "rofi"
    "tmux-custom-plugins"
    "wallpapers"
    "starship.toml"
)

# Function to stow dotfiles
stow_dotfiles() {
    for dir in "${DOTFILES_DIRS[@]}"; do
        if [ -d "$DOTFILES_DIR/$dir" ]; then
            stow -v --target="$TARGET_DIR" --dir="$DOTFILES_DIR" "$dir"
            echo "Stowed $dir"
        else
            echo "Directory $dir does not exist in $DOTFILES_DIR"
        fi
    done
}

# Base directory for top-level dotfiles
DOTFILES_TOP_DIR="$SCRIPT_DIR"

# List of top-level dotfiles
DOTFILES_TOP=(
    ".tmux.conf"
    ".zshrc"
    ".triplea.zsh"
    ".gitconfig"
    # Add other top-level dotfiles here
)

# Function to stow top-level dotfiles
stow_top_dotfiles() {
    for file in "${DOTFILES_TOP[@]}"; do
        if [ -e "$DOTFILES_TOP_DIR/$file" ]; then
            stow -v --target="$HOME" --dir="$DOTFILES_TOP_DIR" "$file"
            echo "Stowed $file"
        else
            echo "File $file does not exist in $DOTFILES_TOP_DIR"
        fi
    done
}

# Execute the stow functions
stow_dotfiles
stow_top_dotfiles

echo "All dotfiles stowing complete."
