live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
decorations = "buttonless"
dynamic_padding = false
# padding.x = 20

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s 'TripleA'"]
