live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11

  [font.normal]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Italic"

[mouse]
hide_when_typing = true

  [[mouse.bindings]]
  action = "PasteSelection"
  mouse = "Middle"

[window]
decorations = "buttonless"
dynamic_padding = false

[shell]
program = "/usr/bin/zsh"
args = [ "-l", "-c", "tmux attach || tmux new -s 'TripleA'" ]
